name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Vet
      run: go vet ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.2.2

    - uses: gwatts/go-coverage-action@v2
      id: coverage
      with:
        # Optional coverage threshold
        # use fail-coverage to determine what should happen below this threshold
        coverage-threshold: 100
        cover-pkg: ./...
        add-comment: false
        fail-coverage: false
        
    - name: Update coverage badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      if: github.ref_name == 'main'
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 63d4999a653a0555c9806062b40c0139
        filename: coverage.json
        label: Test Coverage
        message: ${{ steps.coverage.outputs.coverage-pct-1dp }}%
        color: ${{ steps.coverage.outputs.meets-threshold == 'true' && 'green' || 'red' }}
        
    - name: Generate coverage tree map
      run: | 
        go run github.com/nikolaydubina/go-cover-treemap@latest \
            -coverprofile ${{ steps.coverage.outputs.gocov-agg-pathname }} \
            -only-folders=true >/tmp/treemap.svg
